"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Activity, Waves, Cpu, Zap, TrendingUp, Heart } from "lucide-react"

interface TerminologyCard {
  icon: React.ElementType
  title: string
  description: string
  details: string[]
}

const terminologies: TerminologyCard[] = [
  {
    icon: Heart,
    title: "Blood Pressure (BP)",
    description: "The force of blood against the walls of arteries as the heart pumps.",
    details: [
      "Systolic Blood Pressure (SBP): Maximum pressure during heart contraction",
      "Diastolic Blood Pressure (DBP): Minimum pressure when heart is at rest",
      "Normal range: SBP < 120 mmHg, DBP < 80 mmHg",
      "Measured in millimeters of mercury (mmHg)",
    ],
  },
  {
    icon: Activity,
    title: "Photoplethysmography (PPG)",
    description: "A non-invasive optical technique to detect blood volume changes.",
    details: [
      "Uses light to measure blood flow in tissues",
      "Common in smartwatches and fitness trackers",
      "Detects pulse rate and blood volume changes",
      "Can estimate heart rate variability and oxygen saturation",
    ],
  },
  {
    icon: Waves,
    title: "Electrocardiography (ECG)",
    description: "A test that records the electrical activity of the heart.",
    details: [
      "Measures electrical signals generated by heart muscle",
      "Shows heart rhythm and detects abnormalities",
      "Records P, QRS, and T waves representing heart cycles",
      "Used to calculate heart rate and detect arrhythmias",
    ],
  },
  {
    icon: Cpu,
    title: "Cuffless Monitoring",
    description: "Blood pressure measurement without using an inflatable cuff.",
    details: [
      "Eliminates discomfort from cuff inflation",
      "Enables continuous monitoring throughout the day",
      "Suitable for wearable devices and long-term tracking",
      "Uses physiological signals like PPG and ECG",
    ],
  },
  {
    icon: Zap,
    title: "Signal Processing",
    description: "Analysis and manipulation of physiological signals to extract meaningful information.",
    details: [
      "Filters noise and artifacts from raw signals",
      "Extracts features like peaks, intervals, and waveforms",
      "Prepares data for machine learning algorithms",
      "Ensures signal quality and reliability",
    ],
  },
  {
    icon: TrendingUp,
    title: "Machine Learning",
    description: "Artificial intelligence technique that learns patterns from data.",
    details: [
      "Deep learning models analyze PPG and ECG patterns",
      "Maps signal features to blood pressure values",
      "Continuously improves accuracy with more data",
      "Enables personalized and adaptive monitoring",
    ],
  },
]

export function TerminologiesSection() {
  return (
    <section id="terminologies" className="py-20 bg-background">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-4xl md:text-5xl font-bold tracking-tight mb-4 bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent">
            Terminologies
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Understanding the key concepts and technologies behind PulseAI
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {terminologies.map((term) => (
            <Card
              key={term.title}
              className="relative overflow-hidden hover:shadow-xl hover:border-primary/20 transition-all duration-300 group h-full"
            >
              <div className="absolute inset-0 bg-gradient-to-br from-blue-500/0 via-purple-500/0 to-pink-500/0 group-hover:from-blue-500/5 group-hover:via-purple-500/5 group-hover:to-pink-500/5 transition-all duration-300" />
              <CardHeader className="relative z-10">
                <div className="flex items-center gap-3 mb-2">
                  <div className="p-2.5 rounded-lg bg-gradient-to-br from-primary/10 to-primary/5 text-primary group-hover:scale-110 transition-transform duration-300">
                    <term.icon className="h-5 w-5" />
                  </div>
                  <CardTitle className="text-xl">{term.title}</CardTitle>
                </div>
                <CardDescription className="text-base">{term.description}</CardDescription>
              </CardHeader>
              <CardContent className="relative z-10">
                <ul className="space-y-2.5 text-sm text-muted-foreground">
                  {term.details.map((detail, index) => (
                    <li key={index} className="flex items-start gap-2.5">
                      <span className="text-primary mt-1.5 text-xs">•</span>
                      <span className="leading-relaxed">{detail}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* How PulseAI Works */}
        <div className="mt-16">
          <Card className="relative overflow-hidden border-2 bg-gradient-to-br from-background via-background to-muted/20 hover:shadow-2xl transition-all duration-300">
            <div className="absolute inset-0 bg-gradient-to-br from-blue-500/5 via-purple-500/5 to-pink-500/5" />
            <CardHeader className="relative z-10">
              <CardTitle className="text-2xl flex items-center gap-3">
                <div className="p-2 rounded-lg bg-gradient-to-br from-blue-500/20 to-purple-500/20">
                  <Zap className="h-6 w-6 text-primary" />
                </div>
                How PulseAI Works
              </CardTitle>
              <CardDescription className="text-base">Our approach to cuffless blood pressure estimation</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6 relative z-10">
              <div className="space-y-6 text-muted-foreground">
                <div className="flex gap-4 group">
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 text-white flex items-center justify-center font-bold text-sm group-hover:scale-110 transition-transform duration-300 shadow-lg">
                    1
                  </div>
                  <div>
                    <h4 className="font-semibold text-foreground mb-2 text-lg">Signal Acquisition</h4>
                    <p className="leading-relaxed">
                      PulseAI collects real-time PPG and ECG signals from sensors. These signals capture
                      cardiovascular activity and blood volume changes in the body.
                    </p>
                  </div>
                </div>
                <div className="flex gap-4 group">
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-gradient-to-br from-purple-500 to-pink-600 text-white flex items-center justify-center font-bold text-sm group-hover:scale-110 transition-transform duration-300 shadow-lg">
                    2
                  </div>
                  <div>
                    <h4 className="font-semibold text-foreground mb-2 text-lg">Signal Processing</h4>
                    <p className="leading-relaxed">
                      Raw signals are filtered and processed to remove noise and artifacts. Key features
                      such as pulse rate, R-R intervals, and waveform characteristics are extracted.
                    </p>
                  </div>
                </div>
                <div className="flex gap-4 group">
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-gradient-to-br from-pink-500 to-red-600 text-white flex items-center justify-center font-bold text-sm group-hover:scale-110 transition-transform duration-300 shadow-lg">
                    3
                  </div>
                  <div>
                    <h4 className="font-semibold text-foreground mb-2 text-lg">Feature Extraction</h4>
                    <p className="leading-relaxed">
                      Advanced algorithms analyze the processed signals to identify patterns and extract
                      features that correlate with blood pressure measurements.
                    </p>
                  </div>
                </div>
                <div className="flex gap-4 group">
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-gradient-to-br from-blue-600 to-cyan-600 text-white flex items-center justify-center font-bold text-sm group-hover:scale-110 transition-transform duration-300 shadow-lg">
                    4
                  </div>
                  <div>
                    <h4 className="font-semibold text-foreground mb-2 text-lg">Machine Learning Prediction</h4>
                    <p className="leading-relaxed">
                      Deep learning models trained on extensive datasets map the extracted features to
                      systolic and diastolic blood pressure values, providing accurate estimates in real-time.
                    </p>
                  </div>
                </div>
                <div className="flex gap-4 group">
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-gradient-to-br from-cyan-500 to-blue-600 text-white flex items-center justify-center font-bold text-sm group-hover:scale-110 transition-transform duration-300 shadow-lg">
                    5
                  </div>
                  <div>
                    <h4 className="font-semibold text-foreground mb-2 text-lg">Display & Monitoring</h4>
                    <p className="leading-relaxed">
                      The estimated blood pressure values are displayed in real-time, allowing for continuous
                      monitoring without the need for periodic cuff measurements.
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
