"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Activity, Waves, Cpu, Zap, TrendingUp, Heart } from "lucide-react"

interface TerminologyCard {
  icon: React.ElementType
  title: string
  description: string
  details: string[]
}

const terminologies: TerminologyCard[] = [
  {
    icon: Heart,
    title: "Blood Pressure (BP)",
    description: "The force of blood against the walls of arteries as the heart pumps.",
    details: [
      "Systolic Blood Pressure (SBP): Maximum pressure during heart contraction",
      "Diastolic Blood Pressure (DBP): Minimum pressure when heart is at rest",
      "Normal range: SBP < 120 mmHg, DBP < 80 mmHg",
      "Measured in millimeters of mercury (mmHg)",
    ],
  },
  {
    icon: Activity,
    title: "Photoplethysmography (PPG)",
    description: "A non-invasive optical technique to detect blood volume changes.",
    details: [
      "Uses light to measure blood flow in tissues",
      "Common in smartwatches and fitness trackers",
      "Detects pulse rate and blood volume changes",
      "Can estimate heart rate variability and oxygen saturation",
    ],
  },
  {
    icon: Waves,
    title: "Electrocardiography (ECG)",
    description: "A test that records the electrical activity of the heart.",
    details: [
      "Measures electrical signals generated by heart muscle",
      "Shows heart rhythm and detects abnormalities",
      "Records P, QRS, and T waves representing heart cycles",
      "Used to calculate heart rate and detect arrhythmias",
    ],
  },
  {
    icon: Cpu,
    title: "Cuffless Monitoring",
    description: "Blood pressure measurement without using an inflatable cuff.",
    details: [
      "Eliminates discomfort from cuff inflation",
      "Enables continuous monitoring throughout the day",
      "Suitable for wearable devices and long-term tracking",
      "Uses physiological signals like PPG and ECG",
    ],
  },
  {
    icon: Zap,
    title: "Signal Processing",
    description: "Analysis and manipulation of physiological signals to extract meaningful information.",
    details: [
      "Filters noise and artifacts from raw signals",
      "Extracts features like peaks, intervals, and waveforms",
      "Prepares data for machine learning algorithms",
      "Ensures signal quality and reliability",
    ],
  },
  {
    icon: TrendingUp,
    title: "Machine Learning",
    description: "Artificial intelligence technique that learns patterns from data.",
    details: [
      "Deep learning models analyze PPG and ECG patterns",
      "Maps signal features to blood pressure values",
      "Continuously improves accuracy with more data",
      "Enables personalized and adaptive monitoring",
    ],
  },
]

export function TerminologiesSection() {
  return (
    <section id="terminologies" className="py-24 bg-gradient-to-b from-background via-muted/20 to-background">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16 animate-fade-in-up">
          <h2 className="text-5xl md:text-6xl lg:text-7xl font-extrabold tracking-tight mb-6 bg-gradient-to-r from-primary via-purple-600 to-pink-600 bg-clip-text text-transparent font-display pb-2">
            Terminologies
          </h2>
          <p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto font-medium font-ui">
            Understanding the key concepts and technologies behind PulseAI
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {terminologies.map((term, index) => (
            <Card
              key={term.title}
              className="relative overflow-hidden border-2 border-primary/10 bg-gradient-to-br from-card via-card to-primary/5 hover:shadow-2xl hover:shadow-primary/20 hover:border-primary/30 transition-all duration-500 group h-full animate-fade-in-up"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className="absolute inset-0 bg-gradient-to-br from-primary/0 via-purple-500/0 to-pink-500/0 group-hover:from-primary/10 group-hover:via-purple-500/10 group-hover:to-pink-500/10 transition-all duration-500" />
              <CardHeader className="relative z-10 pb-4">
                <div className="flex items-center gap-4 mb-3">
                  <div className="p-3 rounded-xl bg-gradient-to-br from-primary/20 to-purple-500/20 text-primary shadow-lg shadow-primary/20 group-hover:scale-110 group-hover:rotate-6 transition-all duration-300">
                    <term.icon className="h-6 w-6" />
                  </div>
                  <CardTitle className="text-2xl font-extrabold font-display">
                    {term.title}
                  </CardTitle> 
                </div>
                <CardDescription className="text-lg font-medium">{term.description}</CardDescription>
              </CardHeader>
              <CardContent className="relative z-10">
                <ul className="space-y-3 text-base text-muted-foreground font-ui">
                  {term.details.map((detail, index) => (
                    <li key={index} className="flex items-start gap-3">
                      <span className="text-primary mt-2 text-lg font-bold">•</span>
                      <span className="leading-relaxed">{detail}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* How PulseAI Works */}
        <div className="mt-20 animate-fade-in-up">
          <Card className="relative overflow-hidden border-2 border-primary/20 bg-gradient-to-br from-card via-card to-primary/5 hover:shadow-2xl hover:shadow-primary/20 transition-all duration-500">
            <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-purple-500/5 to-pink-500/5" />
            <CardHeader className="relative z-10 pb-6">
              <CardTitle className="text-3xl md:text-4xl font-extrabold flex items-center gap-4 font-display">
                <div className="p-3 rounded-xl bg-gradient-to-br from-primary/20 to-purple-500/20 shadow-lg shadow-primary/20">
                  <Zap className="h-8 w-8 text-primary" />
                </div>
                How PulseAI Works
              </CardTitle>
              <CardDescription className="text-xl font-medium mt-2">Our approach to cuffless blood pressure estimation</CardDescription>
            </CardHeader>
            <CardContent className="space-y-8 relative z-10">
              <div className="space-y-8">
                <div className="flex gap-6 group">
                  <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-500 to-purple-600 text-white flex items-center justify-center font-extrabold text-lg group-hover:scale-110 group-hover:rotate-6 transition-all duration-300 shadow-xl shadow-blue-500/30">
                    1
                  </div>
                  <div>
                    <h4 className="font-extrabold text-foreground mb-3 text-2xl font-display">
                      Signal Acquisition
                    </h4>
                    <p className="leading-relaxed text-lg font-medium text-muted-foreground font-ui">
                      PulseAI collects real-time PPG and ECG signals from sensors. These signals capture
                      cardiovascular activity and blood volume changes in the body.
                    </p> 
                  </div>
                </div>
                <div className="flex gap-6 group">
                  <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-gradient-to-br from-purple-500 to-pink-600 text-white flex items-center justify-center font-extrabold text-lg group-hover:scale-110 group-hover:rotate-6 transition-all duration-300 shadow-xl shadow-purple-500/30">
                    2
                  </div>
                  <div>
                    <h4 className="font-extrabold text-foreground mb-3 text-2xl font-display">
                      Signal Processing
                    </h4>
                    <p className="leading-relaxed text-lg font-medium text-muted-foreground font-ui">
                      Raw signals are filtered and processed to remove noise and artifacts. Key features
                      such as pulse rate, R-R intervals, and waveform characteristics are extracted.
                    </p>
                  </div>
                </div>
                <div className="flex gap-6 group">
                  <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-gradient-to-br from-pink-500 to-red-600 text-white flex items-center justify-center font-extrabold text-lg group-hover:scale-110 group-hover:rotate-6 transition-all duration-300 shadow-xl shadow-pink-500/30">
                    3
                  </div>
                  <div>
                    <h4 className="font-extrabold text-foreground mb-3 text-2xl font-display">
                      Feature Extraction
                    </h4>
                    <p className="leading-relaxed text-lg font-medium text-muted-foreground font-ui">
                      Advanced algorithms analyze the processed signals to identify patterns and extract
                      features that correlate with blood pressure measurements.
                    </p>
                  </div>
                </div>
                <div className="flex gap-6 group">
                  <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-600 text-white flex items-center justify-center font-extrabold text-lg group-hover:scale-110 group-hover:rotate-6 transition-all duration-300 shadow-xl shadow-cyan-500/30">
                    4
                  </div>
                  <div>
                    <h4 className="font-extrabold text-foreground mb-3 text-2xl font-display">
                      Machine Learning Prediction
                    </h4>
                    <p className="leading-relaxed text-lg font-medium text-muted-foreground font-ui">
                      Deep learning models trained on extensive datasets map the extracted features to
                      systolic and diastolic blood pressure values, providing accurate estimates in real-time.
                    </p>
                  </div>
                </div>
                <div className="flex gap-6 group">
                  <div className="flex-shrink-0 w-14 h-14 rounded-2xl bg-gradient-to-br from-cyan-500 to-blue-600 text-white flex items-center justify-center font-extrabold text-lg group-hover:scale-110 group-hover:rotate-6 transition-all duration-300 shadow-xl shadow-blue-500/30">
                    5
                  </div>
                  <div>
                    <h4 className="font-extrabold text-foreground mb-3 text-2xl font-display">
                      Display & Monitoring
                    </h4>
                    <p className="leading-relaxed text-lg font-medium text-muted-foreground font-ui">
                      The estimated blood pressure values are displayed in real-time, allowing for continuous
                      monitoring without the need for periodic cuff measurements.
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  )
}
