"""Bundle local code into a self-contained Kaggle kernel (no git commit needed).

Usage:
    uv run scripts/kaggle_push.py            # regenerate kag-push/ from local files
    kaggle kernels push -p kag-push          # upload + run on Kaggle (T4, dataset attached)

Edit src/models/*.py locally, re-run this script, push. Zero git history.
"""
import base64
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "kag-push"

# Only what's needed to train. Dataset stays on Kaggle (/kaggle/input mount).
FILES = ["pyproject.toml"] + sorted(str(p.relative_to(ROOT)) for p in (ROOT / "src/models").glob("*.py"))

payload = {}
for rel in FILES:
    payload[rel] = base64.b64encode((ROOT / rel).read_bytes()).decode()

INTRO = "# Cuffless BP — local bundle (no git)\nGenerated by `scripts/kaggle_push.py` from your working tree. Dataset: `yesellee/mimiciii-pulsedb` (attached via metadata)."

# Real writer cell (built with actual payload, repr-safe since b64 is ASCII)
writer_src = (
    "import base64, os\n"
    f"payload = {payload!r}\n"
    "for rel, b64 in payload.items():\n"
    "    p = os.path.join('/kaggle/working/pkg', rel)\n"
    "    os.makedirs(os.path.dirname(p), exist_ok=True)\n"
    "    open(p, 'wb').write(base64.b64decode(b64))\n"
    "print(f'wrote {len(payload)} files')\n"
)
train_src = (
    "%cd /kaggle/working/pkg\n"
    "!uv venv --python 3.11 -q && uv sync -q\n"
    "!uv run src/models/train_attention.py"
)

def cell(kind, src):
    return {"cell_type": kind, "metadata": {},
            ("source" if kind == "code" else "source"): [src] if kind == "markdown" else [src],
            **({"execution_count": None, "outputs": []} if kind == "code" else {})}

nb = {"cells": [cell("markdown", INTRO), cell("code", "!pip install -q uv"),
                cell("code", writer_src), cell("code", train_src)],
      "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                   "language_info": {"name": "python", "version": "3.11"}},
      "nbformat": 4, "nbformat_minor": 5}

OUT.mkdir(exist_ok=True)
(OUT / "cuffless-bp-estimation.ipynb").write_text(json.dumps(nb))
shutil.copy("/tmp/kagpull/kernel-metadata.json", OUT / "kernel-metadata.json")
print(f"bundled {len(payload)} files -> {OUT}")
print("push with: kaggle kernels push -p kag-push")
