"""Bundle local code into a self-contained Kaggle kernel (no git commit needed).

Features:
- Safeguards against duplicate GPU sessions burning Kaggle free usage limit.
- Checks running kernel status before pushing.
- Ensures checkpoints & plots are mirrored to /kaggle/working for automatic Version Outputs.
- Supports attention ablation toggle (--ablate-attention).
- Supports --status and --cancel commands.

Usage:
    uv run scripts/kaggle_push.py                    # Regenerate kag-push/ notebook bundle
    uv run scripts/kaggle_push.py --push             # Check status & safely push to Kaggle
    uv run scripts/kaggle_push.py --push --force     # Force push even if another session is running
    uv run scripts/kaggle_push.py --status           # Check current kernel run status
    uv run scripts/kaggle_push.py --cancel           # Cancel running kernel on Kaggle
    uv run scripts/kaggle_push.py --ablate-attention # Bundle kernel with attention ablated
"""
import argparse
import base64
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "kag-push"
KERNEL_ID = "arwinstha/cuffless-bp-estimation"


def get_kernel_status():
    """Get current status of Kaggle kernel via kaggle CLI."""
    try:
        res = subprocess.run(
            ["kaggle", "kernels", "status", KERNEL_ID],
            capture_output=True, text=True, check=False
        )
        output = (res.stdout + res.stderr).strip()
        return output
    except FileNotFoundError:
        return "kaggle CLI not found in PATH"
    except Exception as e:
        return f"Error checking status: {e}"


def cancel_kernel():
    """Cancel any running Kaggle kernel."""
    print(f"🛑 Attempting to cancel kernel: {KERNEL_ID}...")
    try:
        res = subprocess.run(
            ["kaggle", "kernels", "cancel", KERNEL_ID],
            capture_output=True, text=True, check=False
        )
        print((res.stdout + res.stderr).strip())
    except Exception as e:
        print(f"❌ Failed to cancel kernel: {e}")


def build_bundle(ablate_attention=False):
    """Bundle local code into self-contained notebook."""
    # Only what's needed to train. Dataset stays on Kaggle (/kaggle/input mount).
    files = ["pyproject.toml"] + sorted(str(p.relative_to(ROOT)) for p in (ROOT / "src/models").glob("*.py"))
    
    payload = {}
    for rel in files:
        payload[rel] = base64.b64encode((ROOT / rel).read_bytes()).decode()
    
    train_cmd = "!uv run src/models/train_attention.py --ablate-attention" if ablate_attention else "!uv run src/models/train_attention.py"
    mode_label = "Attention Ablation (Simple CNN+GRU)" if ablate_attention else "Physiology-informed CNN-LSTM with Attention"
    
    intro = (
        f"# Cuffless BP — Cloud Training Bundle\n"
        f"Generated by `scripts/kaggle_push.py` from local working tree.\n\n"
        f"- **Model Mode**: {mode_label}\n"
        f"- **Dataset**: `yesellee/mimiciii-pulsedb`\n"
        f"- **Persistence**: Headless execution. Outputs automatically saved to Kaggle Version Outputs upon completion.\n"
    )
    
    writer_src = (
        "import base64, os\n"
        f"payload = {payload!r}\n"
        "for rel, b64 in payload.items():\n"
        "    p = os.path.join('/kaggle/working/pkg', rel)\n"
        "    os.makedirs(os.path.dirname(p), exist_ok=True)\n"
        "    open(p, 'wb').write(base64.b64decode(b64))\n"
        "print(f'✅ Wrote {len(payload)} files to /kaggle/working/pkg')\n"
    )
    
    train_src = (
        "%cd /kaggle/working/pkg\n"
        "!uv venv --python 3.11 -q && uv sync -q\n"
        f"{train_cmd}\n"
        "\n# Mirror all checkpoints and plots to /kaggle/working root for Version Outputs\n"
        "import shutil, glob, os\n"
        "for item in glob.glob('/kaggle/working/checkpoints/*'):\n"
        "    dst = os.path.join('/kaggle/working', os.path.basename(item))\n"
        "    if not os.path.exists(dst):\n"
        "        if os.path.isdir(item):\n"
        "            shutil.copytree(item, dst, dirs_exist_ok=True)\n"
        "        else:\n"
        "            shutil.copy2(item, dst)\n"
        "print('🎉 Training complete! Artifacts mirrored to /kaggle/working for Version Outputs.')\n"
    )
    
    def cell(kind, src):
        return {
            "cell_type": kind,
            "metadata": {},
            "source": [src] if kind == "markdown" else [src],
            **({"execution_count": None, "outputs": []} if kind == "code" else {})
        }
    
    nb = {
        "cells": [
            cell("markdown", intro),
            cell("code", "!pip install -q uv"),
            cell("code", writer_src),
            cell("code", train_src)
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"}
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }
    
    OUT.mkdir(exist_ok=True)
    (OUT / "cuffless-bp-estimation.ipynb").write_text(json.dumps(nb, indent=2))
    
    # Preserve or copy kernel-metadata.json
    meta_src = Path("/tmp/kagpull/kernel-metadata.json")
    meta_dst = OUT / "kernel-metadata.json"
    if meta_src.exists():
        shutil.copy(meta_src, meta_dst)
    elif not meta_dst.exists():
        default_meta = {
            "id": KERNEL_ID,
            "title": "Cuffless BP Estimation",
            "code_file": "cuffless-bp-estimation.ipynb",
            "language": "python",
            "kernel_type": "notebook",
            "is_private": True,
            "enable_gpu": True,
            "enable_tpu": False,
            "enable_internet": True,
            "keywords": ["gpu"],
            "dataset_sources": ["yesellee/mimiciii-pulsedb"]
        }
        meta_dst.write_text(json.dumps(default_meta, indent=2))
    
    print(f"📦 Bundled {len(payload)} files -> {OUT}")
    print(f"   Model mode: {mode_label}")


def push_to_kaggle(force=False):
    """Push bundle to Kaggle after verifying session safety."""
    status = get_kernel_status()
    print(f"📊 Current Kaggle Kernel Status:\n   {status}")
    
    is_running = any(k in status.lower() for k in ["running", "queued", "draft"])
    
    if is_running and not force:
        print("\n⚠️  WARNING: A session is already RUNNING or QUEUED on Kaggle!")
        print("   Running multiple sessions simultaneously burns your free GPU quota (30h/week).")
        print("   To cancel the running session, run:")
        print("       uv run scripts/kaggle_push.py --cancel")
        print("   To force push anyway, run:")
        print("       uv run scripts/kaggle_push.py --push --force")
        sys.exit(1)
    
    print(f"\n🚀 Pushing kernel to Kaggle ({KERNEL_ID})...")
    res = subprocess.run(["kaggle", "kernels", "push", "-p", str(OUT)], check=False)
    if res.returncode == 0:
        print("\n✅ Successfully pushed to Kaggle!")
        print("🌐 Headless cloud execution has started.")
        print("💡 You CAN close your laptop or disconnect now. Kaggle continues running on the cloud.")
        print("💡 When finished, Kaggle will automatically save a new Version with all outputs.")
        print(f"💡 Monitor status anytime with: uv run scripts/kaggle_push.py --status")
    else:
        print(f"\n❌ Push failed with return code {res.returncode}")


def main():
    parser = argparse.ArgumentParser(description="Kaggle push & bundle utility for Cuffless BP")
    parser.add_argument("--push", action="store_true", help="Push kernel to Kaggle after bundling")
    parser.add_argument("--force", action="store_true", help="Force push even if a session is currently running")
    parser.add_argument("--status", action="store_true", help="Check current kernel status on Kaggle")
    parser.add_argument("--cancel", action="store_true", help="Cancel running kernel on Kaggle")
    parser.add_argument("--ablate-attention", action="store_true", help="Configure bundle to train without attention")
    args = parser.parse_args()
    
    if args.status:
        print(f"📊 Kaggle Kernel Status for {KERNEL_ID}:")
        print(f"   {get_kernel_status()}")
        return
    
    if args.cancel:
        cancel_kernel()
        return
    
    build_bundle(ablate_attention=args.ablate_attention)
    
    if args.push:
        push_to_kaggle(force=args.force)
    else:
        print("\n💡 Ready to push. Run:")
        print("   uv run scripts/kaggle_push.py --push")


if __name__ == "__main__":
    main()
